# Generated by Django 5.2 on 2025-04-10 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='description',
        ),
    ]
