# Generated by Django 5.2 on 2025-04-10 11:15

from django.db import migrations

def create_initial_statuses(apps, schema_editor):
    # Obtener el modelo Status dinámicamente
    Status = apps.get_model('issues', 'Status')
    Types = apps.get_model('issues', 'Types')
    Severities = apps.get_model('issues', 'Severities')
    Priorities = apps.get_model('issues', 'Priorities')

    # Crear las instancias iniciales
    statuses = [
        {'nombre': 'New', 'slug': 'new', 'color': '#FF0000'},
        {'nombre': 'In Progress', 'slug': 'in_progress', 'color': '#00FF00'},
        {'nombre': 'Ready for Test', 'slug': 'ready_for_test', 'color': '#0000FF'},
        {'nombre': 'Closed', 'slug': 'closed', 'color': '#FB9026'},
    ]

    for status in statuses:
        Status.objects.create(**status)

    types = [
        {'nombre': 'Bug', 'color': '#FF5733'},
        {'nombre': 'Question', 'color': '#33FF57'},
        {'nombre': 'Improvement', 'color': '#3357FF'},
    ]
    for ttype in types:
        Types.objects.create(**ttype)

    # Crear las instancias iniciales para Severities
    severities = [
        {'nombre': 'Critical', 'color': '#FF0000'},
        {'nombre': 'Important', 'color': '#FFA500'},
        {'nombre': 'Normal', 'color': '#FFFF00'},
        {'nombre': 'Minor', 'color': '#00FF00'},
    ]
    for severity in severities:
        Severities.objects.create(**severity)

    # Crear las instancias iniciales para Priorities
    priorities = [
        {'nombre': 'Urgent', 'color': '#FF0000'},
        {'nombre': 'High', 'color': '#FFA500'},
        {'nombre': 'Medium', 'color': '#FFFF00'},
        {'nombre': 'Low', 'color': '#00FF00'},
    ]
    for priority in priorities:
        Priorities.objects.create(**priority)

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_statuses),
    ]
