# Generated by Django 5.2 on 2025-04-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_priorities_severities_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorities',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='severities',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='types',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
